// cityData.js — shared data for all suburb pages

export const suburbs = [
    "Sydney", "Birchgrove", "Crowns Nest",
    "Parramatta", "Dural", "Croydon Park",
    "Baulkham Hills", "Burwood", "Croydon",
    "Blacktown", "Cabarita", "Bondi",
    "East Killara", "Breakfast Point", "East Lindfield",
    "Dover Heights", "Canada Bay", "East Ryde",
    "Woollarah", "Carlingford", "Eastwood",
    "Paddington", "Castle Hill", "Epping",
    "Abbotsford", "Castle Cove", "Five Dock",
    "Artarmon", "Chatswood", "Gladesville",
    "Ashfield", "Chatswood West", "Gordon",
    "Balmain", "Cherrybrook", "Hunters Hill",
    "Beecroft", "Chiswick", "Kellyville",
    "Bella Vista", "Concord", "Concord West",
    "North Ryde", "Ryde", "Strathfield",
];

export const cityData = {
    "Sydney": {
        image1: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
        image2: "https://images.unsplash.com/photo-1524293568345-75d62c3664f7?w=800&q=80",
        area: "Sydney CBD & Inner City",
        description: "the heart of Australia's largest city, home to iconic landmarks, bustling businesses, and a vibrant mix of residents",
        character: "As Sydney's central hub, the area is home to countless businesses, startups, and households that depend on reliable technology every single day.",
        localTip: "From the CBD's skyscrapers to the inner-city terrace homes of Surry Hills and Darlinghurst, our technicians navigate Sydney's streets daily.",
        services: ["Gaming PC Building & Repair", "Mac & Windows PC Repair ", "Internet & Email Issues", "Hardware Upgrades & Repair", "Software & Device Tutorials", "Network & Wireless Set Up", "CCTV Setup & Servicing", "Data Recovery", "Servers Setup", "Business Phone System Set Up", "Protection From Hackers", "Starlink Set Up"],
        faq: [
            { q: "Do you offer same-day service in Sydney CBD?", a: "Yes! We offer same-day on-site service across the Sydney CBD and surrounding inner-city suburbs. Call (02) 8313 6420 and we'll get a technician to you as fast as possible." },
            { q: "Can you help my Sydney business set up IT infrastructure?", a: "Absolutely. From small offices to larger commercial setups, we handle server configuration, network cabling, cloud integration, and ongoing IT support for Sydney businesses." },
        ],
    },
    "Bondi": {
        image1: "https://images.unsplash.com/photo-1476158085676-e67f57ed9ed7?w=800&q=80",
        image2: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80",
        area: "Eastern Suburbs",
        description: "one of Sydney's most iconic beach suburbs, known for its stunning coastline, café culture, and vibrant community",
        character: "Bondi's mix of creative professionals, small businesses, and families means technology plays a central role in daily life here.",
        localTip: "Whether you're working from your Bondi apartment or running a café on Campbell Parade, our team knows the Eastern Suburbs inside out.",
        services: ["Gaming PC Building & Repair", "Mac & Windows PC Repair ", "Internet & Email Issues", "Hardware Upgrades & Repair", "Software & Device Tutorials", "Network & Wireless Set Up", "CCTV Setup & Servicing", "Data Recovery", "Servers Setup", "Business Phone System Set Up", "Protection From Hackers", "Starlink Set Up"],
        faq: [
            { q: "Can you come to my Bondi apartment for repairs?", a: "Yes, we offer in-home service across Bondi and the Eastern Suburbs. Our technicians come to you — no need to leave your home or office." },
            { q: "My MacBook is running slow — can you fix it?", a: "Definitely! Mac performance issues are one of our most common jobs in Bondi. We diagnose the issue and have it running fast again, often the same day." },
        ],
    },
    "Parramatta": {
        image1: "https://images.unsplash.com/photo-1598887142488-3a6f814e3e1a?w=800&q=80",
        image2: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
        area: "Greater Western Sydney",
        description: "Western Sydney's major commercial and cultural hub, one of Australia's fastest-growing urban centres",
        character: "Parramatta is booming with new businesses, government offices, and a growing residential population — all of which rely heavily on technology infrastructure.",
        localTip: "From Church Street offices to the new Westmead health precinct, our technicians are familiar with every corner of Parramatta.",
        services: ["Gaming PC Building & Repair", "Mac & Windows PC Repair ", "Internet & Email Issues", "Hardware Upgrades & Repair", "Software & Device Tutorials", "Network & Wireless Set Up", "CCTV Setup & Servicing", "Data Recovery", "Servers Setup", "Business Phone System Set Up", "Protection From Hackers", "Starlink Set Up"],
        faq: [
            { q: "Do you support businesses in the Parramatta CBD?", a: "Yes, Parramatta is one of our key service areas. We provide reliable on-site IT support for offices, retail businesses, and government agencies throughout the Parramatta CBD." },
            { q: "Can you help with setting up a new office network in Parramatta?", a: "Absolutely! From router and switch installation to Wi-Fi access point placement and NBN setup, we handle complete office network builds across Parramatta." },
        ],
    },
    "Blacktown": {
        image1: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
        image2: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
        area: "Western Sydney",
        description: "one of Sydney's most culturally diverse and rapidly growing suburbs, at the heart of Western Sydney",
        character: "With a large population of families, small business owners, and students, Blacktown has high demand for affordable, fast, and reliable tech support.",
        localTip: "Our technicians are local to the Blacktown area and understand the community's needs — providing fast, affordable, and friendly service every time.",
        services: ["Gaming PC Building & Repair", "Mac & Windows PC Repair ", "Internet & Email Issues", "Hardware Upgrades & Repair", "Software & Device Tutorials", "Network & Wireless Set Up", "CCTV Setup & Servicing", "Data Recovery", "Servers Setup", "Business Phone System Set Up", "Protection From Hackers", "Starlink Set Up"],
        faq: [
            { q: "How quickly can you come to Blacktown?", a: "We aim to offer same-day or next-day service across Blacktown and surrounding Western Sydney. Call (02) 8313 6420 to book your appointment." },
            { q: "Is your pricing affordable for Blacktown families?", a: "We pride ourselves on competitive, transparent pricing with no hidden fees. We always provide a quote upfront so you know exactly what you're paying." },
        ],
    },
    "Chatswood": {
        image1: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
        image2: "https://images.unsplash.com/photo-1448630360428-65456885c650?w=800&q=80",
        area: "North Shore",
        description: "one of Sydney's most dynamic commercial centres on the North Shore, famous for its shopping precincts and corporate offices",
        character: "Chatswood's thriving business district and tech-savvy residential community make it one of Sydney's most active areas for professional IT support.",
        localTip: "From the corporate towers of Chatswood CBD to residential streets nearby, we cover the entire North Shore corridor.",
        services: ["Gaming PC Building & Repair", "Mac & Windows PC Repair ", "Internet & Email Issues", "Hardware Upgrades & Repair", "Software & Device Tutorials", "Network & Wireless Set Up", "CCTV Setup & Servicing", "Data Recovery", "Servers Setup", "Business Phone System Set Up", "Protection From Hackers", "Starlink Set Up"],
        faq: [
            { q: "Do you offer IT support for businesses in Chatswood?", a: "Yes! Chatswood is a key business hub and we regularly support offices, retail stores, and professional services firms throughout the Chatswood CBD." },
            { q: "Can you fix my computer the same day in Chatswood?", a: "In most cases, yes. We offer same-day on-site service across Chatswood. Call us on (02) 8313 6420 and we'll arrange a technician visit ASAP." },
        ],
    },
    "Balmain": {
        image1: "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?w=800&q=80",
        image2: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
        area: "Inner West",
        description: "a charming Inner West peninsula suburb known for its heritage cottages, waterfront views, and thriving village atmosphere",
        character: "Balmain's community of creative professionals, freelancers, and families all rely on fast and reliable technology — and that's exactly what we deliver.",
        localTip: "Our technicians are familiar with Balmain's unique mix of heritage homes and modern apartments, ensuring minimal disruption during every visit.",
        services: ["Gaming PC Building & Repair", "Mac & Windows PC Repair ", "Internet & Email Issues", "Hardware Upgrades & Repair", "Software & Device Tutorials", "Network & Wireless Set Up", "CCTV Setup & Servicing", "Data Recovery", "Servers Setup", "Business Phone System Set Up", "Protection From Hackers", "Starlink Set Up"],
        faq: [],
    },
    "Paddington": {
        image1: "https://images.unsplash.com/photo-1559329007-40df8a9345d8?w=800&q=80",
        image2: "https://images.unsplash.com/photo-1524293568345-75d62c3664f7?w=800&q=80",
        area: "Eastern Suburbs",
        description: "an elegant Eastern Suburbs neighbourhood famous for its Victorian terrace houses, boutique galleries, and vibrant Oxford Street",
        character: "Paddington's design studios, boutique offices, and residential households all need seamless tech solutions — and TheTechDr delivers just that.",
        localTip: "Whether you're in a terrace on Glenmore Road or a studio near the Paddington Markets, our team arrives promptly and gets the job done.",
        services: ["Gaming PC Building & Repair", "Mac & Windows PC Repair ", "Internet & Email Issues", "Hardware Upgrades & Repair", "Software & Device Tutorials", "Network & Wireless Set Up", "CCTV Setup & Servicing", "Data Recovery", "Servers Setup", "Business Phone System Set Up", "Protection From Hackers", "Starlink Set Up"],
        faq: [],
    },
    "Castle Hill": {
        image1: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&q=80",
        image2: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
        area: "The Hills District",
        description: "a major suburban centre in Sydney's Hills District, known for its family-friendly environment and strong community spirit",
        character: "Castle Hill's growing population of families, professionals, and small businesses create strong demand for fast, reliable, on-site IT support.",
        localTip: "From the Hills Centre to Old Northern Road and beyond, our Castle Hill technicians are never far away when you need urgent tech help.",
        services: ["Gaming PC Building & Repair", "Mac & Windows PC Repair ", "Internet & Email Issues", "Hardware Upgrades & Repair", "Software & Device Tutorials", "Network & Wireless Set Up", "CCTV Setup & Servicing", "Data Recovery", "Servers Setup", "Business Phone System Set Up", "Protection From Hackers", "Starlink Set Up"],
        faq: [],
    },
    "Ashfield": {
        image1: "https://images.unsplash.com/photo-1514214246283-d427a95c5d2f?w=800&q=80",
        image2: "https://images.unsplash.com/photo-1524293568345-75d62c3664f7?w=800&q=80",
        area: "Inner West",
        description: "a multicultural Inner West suburb with a strong community identity, excellent transport links, and a mix of residential and commercial activity",
        character: "Ashfield's diverse community of families, students, and small business owners all rely on technology — and our team is always ready to help.",
        localTip: "From Liverpool Road to Charlotte Street, our Ashfield technicians know the suburb well and provide fast, reliable service to every corner.",
        services: ["Gaming PC Building & Repair", "Mac & Windows PC Repair ", "Internet & Email Issues", "Hardware Upgrades & Repair", "Software & Device Tutorials", "Network & Wireless Set Up", "CCTV Setup & Servicing", "Data Recovery", "Servers Setup", "Business Phone System Set Up", "Protection From Hackers", "Starlink Set Up"],
        faq: [],
    },
};

export const defaultCityData = (city) => ({
    image1: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    image2: "https://images.unsplash.com/photo-1524293568345-75d62c3664f7?w=800&q=80",
    area: "Sydney",
    description: `a wonderful suburb in the greater Sydney metropolitan area`,
    character: `${city}'s residents and businesses rely on technology daily, and TheTechDr is proud to be the trusted local IT expert in this community.`,
    localTip: `Our technicians are familiar with the ${city} area and surrounding suburbs, ensuring fast response times and personalised service.`,
    services: ["PC & Laptop Repair", "Mac & Apple Device Repair", "Virus & Malware Removal", "Wi-Fi & NBN Setup", "Data Recovery & Backup", "Hardware Upgrades", "Home Office IT Setup", "Remote Support", "Printer Configuration", "Windows Reinstallation"],
    faq: [],
});